name: Update Original

on:
  schedule: 
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Commands
      run: |      
        git clone https://github.com/larshp/abapGit /tmp/new
        git checkout original
        cp -r /tmp/new/src src
        git status
