name: Update Original

on:
  schedule: 
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'original'
    - name: Run Commands
      run: |      
        git clone https://github.com/larshp/abapGit /tmp/new
        rm -rf src
        cp -rf /tmp/new/src src
        git status
        git config user.email "ci@abapgit.org"
        git config user.name "CI"
        git add -A
        git commit -m "automatic"
        git push
