name: Upport

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Run Commands
      run: |
        git config user.email "ci@abapgit.org"
        git config user.name "CI"
        git clone https://github.com/abapGit/abapGit /tmp/new
        rm -rf src
        cp -rf /tmp/new/src src
        cp /tmp/new/.abapgit.xml .
        git add -A
        git commit -m "update base"
        git push
        npm install @abaplint/cli
        npx abaplint --fix
        git status
        git add -A
        git commit -m "upport"
        git push
