name: Upport

on:
  schedule: 
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run Commands
      run: |      
        git clone https://github.com/larshp/abapGit /tmp/new
        rm -rf src
        cp -rf /tmp/new/src src
        npm install @abaplint/cli -g
        abaplint --fix
        git status
